"""
04d_train_player_context_minute.py
====================================
Full minute-level player-context architecture + CPU/GPU benchmarking.

Architecture
------------

  Level 1 — Within-game encoder  (shared weights)
    Input : one player's per-minute timeline sequence for a SINGLE past game
            shape (T_game, per_player_feat_dim)
    Model : small causal Transformer  (d=64, nhead=2, layers=2)
    Output: game_embedding = last real token  (dim=64)

  Level 2 — Cross-game encoder  (shared weights)
    Input : K game_embeddings for one player, ordered chronologically
            shape (K, 64)
    Model : non-causal Transformer (all history is already past)
            → mean-pool over K outputs
    Output: player_embedding  (dim=64)

  Level 3 — Game predictor
    Input : [player_token_0..9 | game_frame_0..T-1]
            Uses the same hybrid causal mask as 04c.
    Output: win_prob per game frame

Data requirements
-----------------
  data/processed/features.parquet              — per-minute game features
  data/processed/player_game_summary.parquet   — game-level player index
  data/processed/player_minute_sequences.parquet  (needed for full run)
      generated by: python src/03b_build_player_index.py --include-sequences

Benchmarking
------------
    --benchmark flag: runs a single forward-pass timing + GPU memory estimate
    without full training.  Outputs:
      - forward pass time per batch (ms)
      - GPU VRAM used (if CUDA)
      - estimate of time to train 30 epochs on current dataset

Usage
-----
    # Benchmark only (fast, no training)
    python src/04d_train_player_context_minute.py --benchmark --limit 500

    # Quick smoke test (CPU, small K and sequence length)
    python src/04d_train_player_context_minute.py --limit 5000 --epochs 3 --k 5 --max-seq-len 15

    # Full run on GPU workstation
    python src/04d_train_player_context_minute.py --epochs 30 --k 50
"""

from __future__ import annotations

import argparse
import logging
import math
import os
import pickle
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

# ── Paths ──────────────────────────────────────────────────────────────────────

PROJECT_ROOT     = Path(__file__).resolve().parent.parent
DATA_DIR         = Path(os.environ.get("LOL_DATA_DIR", PROJECT_ROOT / "data" / "processed"))
FEATURES_PATH    = DATA_DIR / "features.parquet"
SUMMARY_PATH     = DATA_DIR / "player_game_summary.parquet"
SEQUENCES_PATH   = DATA_DIR / "player_minute_sequences.parquet"
MODELS_DIR       = PROJECT_ROOT / "models"
LOG_DIR          = PROJECT_ROOT / "logs"

MODELS_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

MODEL_OUT    = MODELS_DIR / "player_context_minute_model.pt"
ARTIFACT_OUT = MODELS_DIR / "player_context_minute_artifacts.pkl"

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_DIR / "04d_train_player_context_minute.log", mode="w"),
    ],
)
log = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

SLOTS = [
    "blue_top", "blue_jungle", "blue_middle", "blue_bottom", "blue_utility",
    "red_top",  "red_jungle",  "red_middle",  "red_bottom",  "red_utility",
]
N_PLAYERS = len(SLOTS)

# Per-player timeline feature columns (from player_minute_sequences.parquet)
SEQ_FEAT_COLS = [
    "total_gold", "xp", "cs_total", "dmg_to_champs",
    "dmg_taken", "level", "time_enemy_cc_ms",
]
SEQ_FEAT_DIM = len(SEQ_FEAT_COLS)

# Game-level feature constants (same as 04b/04c)
METADATA_COLS = {"game_id", "minute", "blue_win", "game_duration_min"}
CAT_SUFFIXES  = ["champion_id", "summoner1_id", "summoner2_id", "keystone", "primary_tree"]

N_THREADS = max(1, (os.cpu_count() or 4) // 2)

# Slot → (team_id, position)
_SLOT_KEY = {
    "blue_top":     (100, "TOP"),
    "blue_jungle":  (100, "JUNGLE"),
    "blue_middle":  (100, "MIDDLE"),
    "blue_bottom":  (100, "BOTTOM"),
    "blue_utility": (100, "UTILITY"),
    "red_top":      (200, "TOP"),
    "red_jungle":   (200, "JUNGLE"),
    "red_middle":   (200, "MIDDLE"),
    "red_bottom":   (200, "BOTTOM"),
    "red_utility":  (200, "UTILITY"),
}
_POS_MAP = {v: k for k, v in _SLOT_KEY.items()}


# ── Building blocks ───────────────────────────────────────────────────────────

class MinutePositionalEncoding(nn.Module):
    def __init__(self, d_model: int, max_minute: int = 120):
        super().__init__()
        pe  = torch.zeros(max_minute + 1, d_model)
        pos = torch.arange(0, max_minute + 1, dtype=torch.float32).unsqueeze(1)
        div = torch.exp(
            torch.arange(0, d_model, 2, dtype=torch.float32)
            * -(math.log(10_000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div[: d_model // 2])
        self.register_buffer("pe", pe)

    def forward(self, x: torch.Tensor, minutes: torch.Tensor) -> torch.Tensor:
        minutes = minutes.clamp(0, self.pe.shape[0] - 1)
        return x + self.pe[minutes]


def _causal_mask(n: int, device: torch.device) -> torch.Tensor:
    return torch.triu(torch.full((n, n), float("-inf"), device=device), diagonal=1)


class WithinGameEncoder(nn.Module):
    """
    Encodes one player's minute-by-minute sequence for a SINGLE past game
    into a game_embedding vector (last real token output).

    Input : (B, T, seq_feat_dim)
    Output: (B, enc_d)
    """

    def __init__(
        self,
        input_dim:  int,
        enc_d:      int   = 64,
        nhead:      int   = 2,
        num_layers: int   = 2,
        ffn_dim:    int   = 128,
        dropout:    float = 0.1,
        max_minute: int   = 120,
    ):
        super().__init__()
        self.input_proj = nn.Linear(input_dim, enc_d)
        self.pos_enc    = MinutePositionalEncoding(enc_d, max_minute)
        enc_layer = nn.TransformerEncoderLayer(
            d_model=enc_d, nhead=nhead, dim_feedforward=ffn_dim,
            dropout=dropout, batch_first=True, norm_first=True,
        )
        self.transformer = nn.TransformerEncoder(enc_layer, num_layers=num_layers)

    def forward(
        self,
        x:       torch.Tensor,  # (B, T, input_dim)
        lengths: torch.Tensor,  # (B,) int — real frames per game
        minutes: torch.Tensor,  # (B, T) int
    ) -> torch.Tensor:          # (B, enc_d)
        T      = x.shape[1]
        device = x.device
        h = self.input_proj(x)
        h = self.pos_enc(h, minutes)
        mask = _causal_mask(T, device)
        h = self.transformer(h, mask=mask)  # (B, T, enc_d)
        # Take last real token
        last_idx = (lengths - 1).clamp(min=0)            # (B,)
        h_last   = h[torch.arange(h.shape[0], device=device), last_idx]
        return h_last  # (B, enc_d)


class CrossGameEncoder(nn.Module):
    """
    Takes K game_embeddings (one per past game) → player_embedding.

    Input : (B, K, enc_d)  — padded; hist_mask marks padding
    Output: (B, player_d)
    """

    def __init__(
        self,
        enc_d:      int,
        player_d:   int   = 64,
        nhead:      int   = 2,
        num_layers: int   = 2,
        ffn_dim:    int   = 128,
        dropout:    float = 0.1,
    ):
        super().__init__()
        self.proj = nn.Linear(enc_d, player_d) if enc_d != player_d else nn.Identity()
        enc_layer = nn.TransformerEncoderLayer(
            d_model=player_d, nhead=nhead, dim_feedforward=ffn_dim,
            dropout=dropout, batch_first=True, norm_first=True,
        )
        self.transformer = nn.TransformerEncoder(enc_layer, num_layers=num_layers)
        self.norm = nn.LayerNorm(player_d)

    def forward(
        self,
        x:         torch.Tensor,  # (B, K, enc_d)
        hist_mask: torch.Tensor,  # (B, K) bool — True = padding
    ) -> torch.Tensor:            # (B, player_d)
        # Ensure at least one unmasked position so softmax never sees all-inf.
        all_masked = hist_mask.all(dim=1)
        safe_mask  = hist_mask.clone()
        safe_mask[all_masked, 0] = False

        h = self.proj(x)
        h = self.transformer(h, src_key_padding_mask=safe_mask)
        real  = (~hist_mask).float().unsqueeze(-1)  # use original mask for pooling
        denom = real.sum(dim=1).clamp(min=1.0)
        h     = (h * real).sum(dim=1) / denom
        return self.norm(h)


class PlayerContextMinuteTransformer(nn.Module):
    """
    Full three-level architecture.

    Forward inputs:
        game_x_cont   (B, T, n_cont)
        game_x_cat    {suf: (B, T, n_players)}
        game_minutes  (B, T) int
        game_lengths  (B,) int
        hist_seqs     (B, n_players, K, T_hist, seq_feat_dim)  — padded
        hist_mins     (B, n_players, K, T_hist) int
        hist_game_len (B, n_players, K) int  — real frames per history game
        hist_k_mask   (B, n_players, K) bool — True = no game at this K slot
    """

    def __init__(
        self,
        n_cont:          int,
        cat_vocab:       dict[str, int],
        cat_embed_dim:   int   = 8,
        enc_d:           int   = 64,
        player_d:        int   = 64,
        game_d:          int   = 128,
        nhead_game:      int   = 4,
        layers_game:     int   = 4,
        ffn_game:        int   = 512,
        nhead_hist:      int   = 2,
        layers_hist:     int   = 2,
        dropout:         float = 0.1,
        max_minute:      int   = 120,
    ):
        super().__init__()
        self.n_players = N_PLAYERS
        self.player_d  = player_d
        self.game_d    = game_d

        # ── Level 1: within-game encoder ──────────────────────────────────────
        self.within_game_enc = WithinGameEncoder(
            input_dim=SEQ_FEAT_DIM, enc_d=enc_d,
            nhead=nhead_hist, num_layers=layers_hist,
            ffn_dim=enc_d * 2, dropout=dropout, max_minute=max_minute,
        )

        # ── Level 2: cross-game encoder ───────────────────────────────────────
        self.cross_game_enc = CrossGameEncoder(
            enc_d=enc_d, player_d=player_d,
            nhead=nhead_hist, num_layers=layers_hist,
            ffn_dim=player_d * 2, dropout=dropout,
        )

        # Project player embedding to game_d
        self.player_proj = nn.Linear(player_d, game_d)

        # ── Categorical embeddings ─────────────────────────────────────────────
        self.cat_embeds = nn.ModuleDict({
            suf: nn.Embedding(vocab + 1, cat_embed_dim, padding_idx=0)
            for suf, vocab in cat_vocab.items()
        })
        n_cats = len(cat_vocab) * N_PLAYERS
        game_proj_in = n_cont + n_cats * cat_embed_dim

        # ── Game projection + positional encoding ─────────────────────────────
        self.game_proj = nn.Linear(game_proj_in, game_d)
        self.pos_enc   = MinutePositionalEncoding(game_d, max_minute)

        # ── Unified game Transformer ───────────────────────────────────────────
        enc_layer = nn.TransformerEncoderLayer(
            d_model=game_d, nhead=nhead_game, dim_feedforward=ffn_game,
            dropout=dropout, batch_first=True, norm_first=True,
        )
        self.game_transformer = nn.TransformerEncoder(enc_layer, num_layers=layers_game)

        # ── Output head ───────────────────────────────────────────────────────
        self.output_head = nn.Linear(game_d, 1)

    @staticmethod
    def _hybrid_mask(n_player: int, n_game: int, device: torch.device) -> torch.Tensor:
        total = n_player + n_game
        mask  = torch.zeros(total, total, device=device)
        mask[:n_player, n_player:] = float("-inf")
        for i in range(n_game):
            mask[n_player + i, n_player + i + 1:] = float("-inf")
        return mask

    def _embed_game(
        self,
        x_cont: torch.Tensor,
        x_cat:  dict[str, torch.Tensor],
    ) -> torch.Tensor:
        parts = [x_cont]
        for suf, emb in self.cat_embeds.items():
            ids = x_cat[suf]                     # (B, T, NP)
            e   = emb(ids)                       # (B, T, NP, D)
            B, T, NP, D = e.shape
            parts.append(e.reshape(B, T, NP * D))
        return torch.cat(parts, dim=-1)

    def forward(
        self,
        game_x_cont:   torch.Tensor,  # (B, T, n_cont)
        game_x_cat:    dict[str, torch.Tensor],
        game_minutes:  torch.Tensor,  # (B, T) int
        game_lengths:  torch.Tensor,  # (B,)
        hist_seqs:     torch.Tensor,  # (B, NP, K, T_h, SEQ_FEAT_DIM)
        hist_mins:     torch.Tensor,  # (B, NP, K, T_h) int
        hist_game_len: torch.Tensor,  # (B, NP, K) int
        hist_k_mask:   torch.Tensor,  # (B, NP, K) bool
    ) -> torch.Tensor:                # (B, T) win prob
        B, T, _ = game_x_cont.shape
        device  = game_x_cont.device
        NP      = self.n_players

        # ── Level 1: encode each past game for each player ────────────────────
        B_NP_K = B * NP * hist_seqs.shape[2]
        K      = hist_seqs.shape[2]
        T_h    = hist_seqs.shape[3]

        flat_seqs = hist_seqs.reshape(B_NP_K, T_h, SEQ_FEAT_DIM)
        flat_mins = hist_mins.reshape(B_NP_K, T_h)
        flat_lens = hist_game_len.reshape(B_NP_K)

        game_embs = self.within_game_enc(flat_seqs, flat_lens, flat_mins)  # (B*NP*K, enc_d)
        game_embs = game_embs.reshape(B * NP, K, -1)                       # (B*NP, K, enc_d)

        # ── Level 2: cross-game → player embedding ─────────────────────────────
        flat_k_mask  = hist_k_mask.reshape(B * NP, K)                      # (B*NP, K)
        player_embs  = self.cross_game_enc(game_embs, flat_k_mask)         # (B*NP, player_d)
        player_embs  = player_embs.reshape(B, NP, self.player_d)           # (B, NP, player_d)
        player_toks  = self.player_proj(player_embs)                       # (B, NP, game_d)

        # ── Level 3: game Transformer ─────────────────────────────────────────
        game_emb = self._embed_game(game_x_cont, game_x_cat)               # (B, T, proj_in)
        game_tok = self.game_proj(game_emb)                                 # (B, T, game_d)
        game_tok = self.pos_enc(game_tok, game_minutes)

        seq   = torch.cat([player_toks, game_tok], dim=1)                  # (B, NP+T, game_d)
        amask = self._hybrid_mask(NP, T, device)
        out   = self.game_transformer(seq, mask=amask)                     # (B, NP+T, game_d)

        x_game = out[:, NP:, :]                                            # (B, T, game_d)
        real   = torch.arange(T, device=device).unsqueeze(0) < game_lengths.unsqueeze(1)
        probs  = torch.sigmoid(self.output_head(x_game).squeeze(-1))
        return probs * real.float()


# ── Data helpers ──────────────────────────────────────────────────────────────

def build_cat_vocab(df: pd.DataFrame, feature_cols: list[str]) -> dict[str, int]:
    vocab: dict[str, int] = {}
    for suf in CAT_SUFFIXES:
        cols = [c for c in feature_cols if c.endswith(f"_{suf}")]
        if not cols:
            continue
        mx = 0
        for col in cols:
            mx = max(mx, int(df[col].max()))
        vocab[suf] = mx
    return vocab


def split_cont_cat(
    feature_cols: list[str], cat_vocab: dict[str, int]
) -> tuple[list[str], dict[str, list[str]]]:
    cat_set: set[str] = set()
    cat_groups: dict[str, list[str]] = {}
    for suf in cat_vocab:
        grp = [c for c in feature_cols if c.endswith(f"_{suf}")]
        if grp:
            cat_groups[suf] = grp
            cat_set.update(grp)
    cont_cols = [c for c in feature_cols if c not in cat_set]
    return cont_cols, cat_groups


def build_seq_lookup(seq_df: pd.DataFrame) -> dict[str, dict]:
    """
    Build a fast lookup: puuid -> {game_id -> (minutes_arr, feats_arr)}.
    Also build puuid -> [(game_creation_ms, game_id)] sorted list using summary.
    """
    # This is called once; seq_df is large so we group efficiently
    log.info("Building per-player sequence lookup (%d rows)...", len(seq_df))
    grouped: dict[str, dict[str, tuple]] = {}
    for (puuid, gid), grp in seq_df.groupby(["puuid", "game_id"], sort=False):
        grp_sorted = grp.sort_values("minute")
        minutes = grp_sorted["minute"].values.astype(np.int32)
        feats   = grp_sorted[SEQ_FEAT_COLS].values.astype(np.float32)
        if puuid not in grouped:
            grouped[puuid] = {}
        grouped[puuid][gid] = (minutes, feats)
    return grouped


def get_player_seq_history(
    puuid:            str,
    game_creation_ms: int,
    chrono:           list[tuple],  # [(gc_ms, gid), ...] sorted asc
    seq_lookup:       dict[str, dict[str, tuple]],
    K:                int,
    max_seq_len:      int,
    seq_feat_dim:     int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Return (seqs, mins, lengths, k_mask) for the K most recent games before
    game_creation_ms.
      seqs    : (K, max_seq_len, seq_feat_dim)
      mins    : (K, max_seq_len) int32
      lengths : (K,) int32 — real frames per game
      k_mask  : (K,) bool  — True = no game at this slot (padding)
    """
    seqs    = np.zeros((K, max_seq_len, seq_feat_dim), dtype=np.float32)
    mins    = np.zeros((K, max_seq_len), dtype=np.int32)
    lengths = np.zeros(K, dtype=np.int32)
    k_mask  = np.ones(K, dtype=bool)

    player_seqs = seq_lookup.get(puuid, {})

    # Find entries strictly before current game
    lo = 0
    for i, (gc, _) in enumerate(chrono):
        if gc < game_creation_ms:
            lo = i + 1
        else:
            break

    relevant = chrono[max(0, lo - K): lo]
    offset   = K - len(relevant)

    for i, (_, gid) in enumerate(relevant):
        entry = player_seqs.get(gid)
        if entry is None:
            continue
        game_mins, game_feats = entry
        T_real = min(len(game_mins), max_seq_len)
        seqs[offset + i, :T_real]    = game_feats[:T_real]
        mins[offset + i, :T_real]    = game_mins[:T_real]
        lengths[offset + i]          = max(T_real, 1)
        k_mask[offset + i]           = False

    return seqs, mins, lengths, k_mask


# ── Dataset ───────────────────────────────────────────────────────────────────

class MinuteLevelDataset(torch.utils.data.Dataset):
    """
    Each item = one game.
    Heavy lifting (sequence construction) is done in __getitem__ lazily.
    """

    def __init__(
        self,
        game_ids:     list,
        df:           pd.DataFrame,
        cont_cols:    list[str],
        cat_groups:   dict[str, list[str]],
        cont_scaler:  StandardScaler,
        cat_vocab:    dict[str, int],
        summary_df:   pd.DataFrame,
        seq_lookup:   dict,  # puuid -> {gid -> (mins, feats)}
        slot_puuids:  dict,  # gid -> {slot -> puuid}
        K:            int,
        max_seq_len:  int,
        chrono_lookup: dict,  # puuid -> [(gc_ms, gid), ...]
    ):
        self.game_ids     = list(game_ids)
        self.df           = df.set_index("game_id") if "game_id" in df.columns else df
        self.cont_cols    = cont_cols
        self.cat_groups   = cat_groups
        self.cont_scaler  = cont_scaler
        self.cat_vocab    = cat_vocab
        self.summary_df   = summary_df
        self.seq_lookup   = seq_lookup
        self.slot_puuids  = slot_puuids
        self.K            = K
        self.max_seq_len  = max_seq_len
        self.chrono_lookup = chrono_lookup

    def __len__(self) -> int:
        return len(self.game_ids)

    def __getitem__(self, idx: int) -> dict:
        gid  = self.game_ids[idx]
        rows = self.df.loc[gid]
        if isinstance(rows, pd.Series):
            rows = rows.to_frame().T
        rows = rows.sort_values("minute")

        T     = len(rows)
        label = float(rows["blue_win"].iloc[0])
        mins  = rows["minute"].values.astype(np.int32)

        x_cont = self.cont_scaler.transform(
            rows[self.cont_cols].values.astype(np.float32)
        )

        x_cat: dict[str, np.ndarray] = {}
        for suf, cols in self.cat_groups.items():
            arr = rows[cols].values.astype(np.int32)
            arr = np.clip(arr, 0, self.cat_vocab[suf])
            x_cat[suf] = arr

        # Game creation timestamp for chronological lookup
        ginfo = self.summary_df[self.summary_df["game_id"] == gid]
        gc_ms = int(ginfo["game_creation_ms"].iloc[0]) if len(ginfo) > 0 else 0

        puuids_for_game = self.slot_puuids.get(gid, {})

        # Player history sequences
        hist_seqs  = np.zeros((N_PLAYERS, self.K, self.max_seq_len, SEQ_FEAT_DIM), np.float32)
        hist_mins  = np.zeros((N_PLAYERS, self.K, self.max_seq_len), np.int32)
        hist_glen  = np.ones((N_PLAYERS, self.K), np.int32)  # default length 1
        hist_kmask = np.ones((N_PLAYERS, self.K), bool)

        for si, slot in enumerate(SLOTS):
            puuid = puuids_for_game.get(slot, "")
            if not puuid:
                continue
            chrono = self.chrono_lookup.get(puuid, [])
            s, m, l, km = get_player_seq_history(
                puuid, gc_ms, chrono, self.seq_lookup,
                self.K, self.max_seq_len, SEQ_FEAT_DIM,
            )
            hist_seqs[si]  = s
            hist_mins[si]  = m
            hist_glen[si]  = l
            hist_kmask[si] = km

        return {
            "x_cont":     torch.from_numpy(x_cont),
            "x_cat":      {s: torch.from_numpy(v) for s, v in x_cat.items()},
            "minutes":    torch.from_numpy(mins),
            "length":     T,
            "label":      label,
            "hist_seqs":  torch.from_numpy(hist_seqs),
            "hist_mins":  torch.from_numpy(hist_mins),
            "hist_glen":  torch.from_numpy(hist_glen),
            "hist_kmask": torch.from_numpy(hist_kmask),
        }


def collate_fn(batch: list[dict]) -> dict:
    max_T = max(b["length"] for b in batch)
    B     = len(batch)
    n_cont = batch[0]["x_cont"].shape[1]
    NP     = batch[0]["hist_seqs"].shape[0]
    K      = batch[0]["hist_seqs"].shape[1]
    T_h    = batch[0]["hist_seqs"].shape[2]

    x_cont_pad   = torch.zeros(B, max_T, n_cont)
    minutes_pad  = torch.zeros(B, max_T, dtype=torch.long)
    lengths      = torch.tensor([b["length"] for b in batch], dtype=torch.long)
    labels       = torch.zeros(B, max_T)
    hist_seqs_b  = torch.zeros(B, NP, K, T_h, SEQ_FEAT_DIM)
    hist_mins_b  = torch.zeros(B, NP, K, T_h, dtype=torch.long)
    hist_glen_b  = torch.ones(B, NP, K, dtype=torch.long)
    hist_kmask_b = torch.ones(B, NP, K, dtype=torch.bool)

    cat_suf   = list(batch[0]["x_cat"].keys())
    n_pl_cat  = {s: batch[0]["x_cat"][s].shape[1] for s in cat_suf}
    x_cat_pad = {s: torch.zeros(B, max_T, n_pl_cat[s], dtype=torch.long) for s in cat_suf}

    for i, b in enumerate(batch):
        T = b["length"]
        x_cont_pad[i, :T]  = b["x_cont"]
        minutes_pad[i, :T] = b["minutes"]
        labels[i, :T]      = b["label"]
        hist_seqs_b[i]     = b["hist_seqs"]
        hist_mins_b[i]     = b["hist_mins"]
        hist_glen_b[i]     = b["hist_glen"]
        hist_kmask_b[i]    = b["hist_kmask"]
        for s in cat_suf:
            x_cat_pad[s][i, :T] = b["x_cat"][s]

    return {
        "x_cont":     x_cont_pad,
        "x_cat":      x_cat_pad,
        "minutes":    minutes_pad,
        "lengths":    lengths,
        "labels":     labels,
        "hist_seqs":  hist_seqs_b,
        "hist_mins":  hist_mins_b,
        "hist_glen":  hist_glen_b,
        "hist_kmask": hist_kmask_b,
    }


# ── Benchmark ─────────────────────────────────────────────────────────────────

def run_benchmark(
    model:   nn.Module,
    loader:  torch.utils.data.DataLoader,
    device:  torch.device,
    use_amp: bool,
    n_batches: int = 10,
) -> None:
    """Profile forward-pass speed and VRAM usage."""
    log.info("=" * 55)
    log.info("BENCHMARK MODE")
    log.info("Device: %s | AMP: %s", device, use_amp)

    model.eval()
    times = []

    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)

    with torch.no_grad():
        for i, batch in enumerate(loader):
            if i >= n_batches:
                break

            x_cont     = batch["x_cont"].to(device)
            x_cat      = {s: v.to(device) for s, v in batch["x_cat"].items()}
            minutes    = batch["minutes"].to(device)
            lengths    = batch["lengths"].to(device)
            hist_seqs  = batch["hist_seqs"].to(device)
            hist_mins  = batch["hist_mins"].to(device)
            hist_glen  = batch["hist_glen"].to(device)
            hist_kmask = batch["hist_kmask"].to(device)

            if device.type == "cuda":
                torch.cuda.synchronize()

            t_start = time.perf_counter()
            with torch.amp.autocast(device_type=device.type, enabled=use_amp, dtype=torch.bfloat16):
                _ = model(
                    x_cont, x_cat, minutes, lengths,
                    hist_seqs, hist_mins, hist_glen, hist_kmask,
                )
            if device.type == "cuda":
                torch.cuda.synchronize()
            t_end = time.perf_counter()
            times.append((t_end - t_start) * 1000)

            if i == 0:
                B, T, _ = x_cont.shape
                log.info("Batch shape: B=%d, T_game=%d, K=%d, T_hist=%d",
                         B, T, hist_seqs.shape[2], hist_seqs.shape[3])

    mean_ms = np.mean(times[1:]) if len(times) > 1 else times[0]  # drop first (JIT warmup)
    log.info("Forward pass: %.1f ms/batch (mean over %d batches)", mean_ms, len(times))

    if device.type == "cuda":
        peak_mb = torch.cuda.max_memory_allocated(device) / 1e6
        log.info("Peak GPU memory: %.1f MB", peak_mb)

    # Extrapolate full-dataset training time
    # (batches per epoch) * (forward + backward, ~3x forward) * n_epochs
    batch_size = loader.batch_size or 32
    n_games_total = 130_000  # typical
    batches_per_epoch = n_games_total / batch_size
    secs_per_epoch = batches_per_epoch * (mean_ms / 1000) * 3  # fwd+bwd ~ 3x
    log.info("Estimate: %.0f s / epoch on %d games (batch=%d, 3x fwd for bwd+opt)",
             secs_per_epoch, n_games_total, batch_size)
    log.info("Estimate: 30 epochs -> %.1f hours", secs_per_epoch * 30 / 3600)

    # History sequence stats
    log.info("=" * 55)


def eval_auc(
    model:  nn.Module,
    loader: torch.utils.data.DataLoader,
    device: torch.device,
    use_amp: bool,
) -> dict[str, float]:
    model.eval()
    cutoffs = {"5m": 5, "10m": 10, "end": 9999}
    preds  = {k: [] for k in cutoffs}
    labels = {k: [] for k in cutoffs}

    with torch.no_grad():
        for batch in loader:
            x_cont     = batch["x_cont"].to(device)
            x_cat      = {s: v.to(device) for s, v in batch["x_cat"].items()}
            minutes    = batch["minutes"].to(device)
            lengths    = batch["lengths"].to(device)
            lab        = batch["labels"].to(device)
            hist_seqs  = batch["hist_seqs"].to(device)
            hist_mins  = batch["hist_mins"].to(device)
            hist_glen  = batch["hist_glen"].to(device)
            hist_kmask = batch["hist_kmask"].to(device)

            with torch.amp.autocast(device_type=device.type, enabled=use_amp, dtype=torch.bfloat16):
                probs = model(
                    x_cont, x_cat, minutes, lengths,
                    hist_seqs, hist_mins, hist_glen, hist_kmask,
                )
            probs = probs.float().nan_to_num(nan=0.5)

            B, T = probs.shape
            for name, cutoff in cutoffs.items():
                for b in range(B):
                    L = lengths[b].item()
                    mins_b  = minutes[b, :L].cpu().numpy()
                    probs_b = probs[b, :L].cpu().float().numpy()
                    lval    = lab[b, 0].item()
                    if cutoff >= 9999:
                        preds[name].append(float(probs_b[-1]))
                    else:
                        idxs = np.where(mins_b <= cutoff)[0]
                        if len(idxs) == 0:
                            continue
                        preds[name].append(float(probs_b[idxs[-1]]))
                    labels[name].append(float(lval))

    return {
        k: roc_auc_score(labels[k], preds[k])
        if len(set(labels[k])) >= 2 else float("nan")
        for k in cutoffs
    }


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--limit",       type=int,   default=0,     help="Max games (0=all)")
    p.add_argument("--epochs",      type=int,   default=20,    help="Max epochs")
    p.add_argument("--patience",    type=int,   default=5)
    p.add_argument("--batch",       type=int,   default=16,    help="Batch size (games)")
    p.add_argument("--lr",          type=float, default=3e-4)
    p.add_argument("--k",           type=int,   default=20,    help="History games per player")
    p.add_argument("--max-seq-len", type=int,   default=27,    help="Max frames per history game")
    p.add_argument("--enc-d",       type=int,   default=64,    help="Within-game encoder dim")
    p.add_argument("--player-d",    type=int,   default=64,    help="Player embedding dim")
    p.add_argument("--game-d",      type=int,   default=128,   help="Game Transformer d_model")
    p.add_argument("--nhead-game",  type=int,   default=4)
    p.add_argument("--layers-game", type=int,   default=4)
    p.add_argument("--ffn-game",    type=int,   default=512)
    p.add_argument("--nhead-hist",  type=int,   default=2)
    p.add_argument("--layers-hist", type=int,   default=2)
    p.add_argument("--dropout",     type=float, default=0.1)
    p.add_argument("--label-smooth",type=float, default=0.05)
    p.add_argument("--workers",     type=int,   default=min(4, N_THREADS))
    p.add_argument("--benchmark",   action="store_true",
                   help="Run benchmark only, no training")
    p.add_argument("--no-sequences", action="store_true",
                   help="Fall back to zero history (tests architecture without sequence data)")
    return p.parse_args()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()
    torch.set_num_threads(N_THREADS)
    t0 = time.time()

    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = device.type == "cuda"
    log.info("Device: %s | AMP: %s", device, use_amp)

    # ── Load game features ────────────────────────────────────────────────────
    log.info("Loading %s ...", FEATURES_PATH)
    df = pd.read_parquet(FEATURES_PATH)
    log.info("Loaded: %d rows x %d cols", len(df), df.shape[1])

    all_games = df["game_id"].unique()
    if args.limit:
        rng = np.random.default_rng(42)
        all_games = rng.choice(all_games, size=min(args.limit, len(all_games)), replace=False)
        df = df[df["game_id"].isin(all_games)]
        log.info("Limited to %d games -> %d rows", len(all_games), len(df))

    rng = np.random.default_rng(42)
    rng.shuffle(all_games)
    n = len(all_games)
    n_tr  = int(n * 0.80)
    n_val = int(n * 0.10)
    train_games = list(all_games[:n_tr])
    val_games   = list(all_games[n_tr: n_tr + n_val])

    feature_cols = [c for c in df.columns if c not in METADATA_COLS]
    cat_vocab    = build_cat_vocab(df, feature_cols)
    cont_cols, cat_groups = split_cont_cat(feature_cols, cat_vocab)

    train_mask  = df["game_id"].isin(set(train_games))
    cont_scaler = StandardScaler()
    cont_scaler.fit(df.loc[train_mask, cont_cols].values.astype(np.float32))
    log.info("Cont cols: %d | Cat groups: %d", len(cont_cols), len(cat_groups))

    # ── Load player summary (for timestamps + slot mapping) ───────────────────
    if not SUMMARY_PATH.exists():
        log.error("Player summary not found: %s — run 03b first", SUMMARY_PATH)
        sys.exit(1)
    log.info("Loading player summary ...")
    summary_df = pd.read_parquet(SUMMARY_PATH)

    # Build slot_puuids mapping
    slot_puuids: dict[str, dict[str, str]] = {}
    for row in summary_df.itertuples(index=False):
        gid  = row.game_id
        key  = (int(row.team_id), str(row.team_position).upper())
        slot = _POS_MAP.get(key)
        if slot is None:
            continue
        if gid not in slot_puuids:
            slot_puuids[gid] = {}
        slot_puuids[gid][slot] = row.puuid

    # ── Load player minute sequences ──────────────────────────────────────────
    seq_lookup:    dict = {}
    chrono_lookup: dict = {}

    if not args.no_sequences and SEQUENCES_PATH.exists():
        log.info("Loading minute sequences from %s ...", SEQUENCES_PATH)
        seq_df = pd.read_parquet(SEQUENCES_PATH)
        log.info("Sequence rows: %d", len(seq_df))
        seq_lookup = build_seq_lookup(seq_df)
        del seq_df  # free RAM

        # Build chrono lookup: puuid -> [(gc_ms, gid), ...] sorted asc
        log.info("Building chronological lookup ...")
        tmp: dict[str, list] = {}
        for row in summary_df.itertuples(index=False):
            p = row.puuid
            if p not in tmp:
                tmp[p] = []
            tmp[p].append((int(row.game_creation_ms), row.game_id))
        for p in tmp:
            tmp[p].sort()
        chrono_lookup = tmp
    else:
        if args.no_sequences:
            log.info("--no-sequences flag: using zero history (architecture test).")
        else:
            log.warning("Sequence file not found: %s", SEQUENCES_PATH)
            log.warning("Running with zero history.  Use 03b --include-sequences to generate it.")

        # Still build chrono from summary (needed for the lookup contract)
        for row in summary_df.itertuples(index=False):
            p = row.puuid
            if p not in chrono_lookup:
                chrono_lookup[p] = []
            chrono_lookup[p].append((int(row.game_creation_ms), row.game_id))
        for p in chrono_lookup:
            chrono_lookup[p].sort()

    # ── Build datasets ────────────────────────────────────────────────────────
    common_kw = dict(
        df=df,
        cont_cols=cont_cols,
        cat_groups=cat_groups,
        cont_scaler=cont_scaler,
        cat_vocab=cat_vocab,
        summary_df=summary_df,
        seq_lookup=seq_lookup,
        slot_puuids=slot_puuids,
        K=args.k,
        max_seq_len=args.max_seq_len,
        chrono_lookup=chrono_lookup,
    )
    log.info("Building datasets: train=%d val=%d", len(train_games), len(val_games))
    train_ds = MinuteLevelDataset(game_ids=train_games, **common_kw)
    val_ds   = MinuteLevelDataset(game_ids=val_games,   **common_kw)

    dl_kw = dict(
        batch_size=args.batch, collate_fn=collate_fn,
        num_workers=args.workers, pin_memory=(device.type == "cuda"),
    )
    train_dl = torch.utils.data.DataLoader(train_ds, shuffle=True,  **dl_kw)
    val_dl   = torch.utils.data.DataLoader(val_ds,   shuffle=False, **dl_kw)

    # ── Instantiate model ─────────────────────────────────────────────────────
    model = PlayerContextMinuteTransformer(
        n_cont       = len(cont_cols),
        cat_vocab    = cat_vocab,
        cat_embed_dim= 8,
        enc_d        = args.enc_d,
        player_d     = args.player_d,
        game_d       = args.game_d,
        nhead_game   = args.nhead_game,
        layers_game  = args.layers_game,
        ffn_game     = args.ffn_game,
        nhead_hist   = args.nhead_hist,
        layers_hist  = args.layers_hist,
        dropout      = args.dropout,
    ).to(device)

    if device.type == "cuda":
        try:
            model = torch.compile(model)
            log.info("torch.compile() applied.")
        except Exception:
            pass

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    log.info("Model params: %s  enc_d=%d player_d=%d game_d=%d",
             f"{n_params:,}", args.enc_d, args.player_d, args.game_d)
    log.info("History: K=%d games x max_seq_len=%d frames", args.k, args.max_seq_len)

    # ── Benchmark mode ────────────────────────────────────────────────────────
    if args.benchmark:
        run_benchmark(model, train_dl, device, use_amp, n_batches=10)
        log.info("Benchmark complete. Exiting.")
        return

    # ── Training ──────────────────────────────────────────────────────────────
    optimizer  = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler  = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    scaler_amp = torch.amp.GradScaler("cuda", enabled=use_amp)

    log.info("Starting training: max %d epochs, patience %d", args.epochs, args.patience)
    log.info("Log: loss=train/val | AUC@5m=tr/val  AUC@10m=tr/val  AUC@end=tr/val")

    best_val_auc = 0.0
    best_state   = None
    patience_cnt = 0

    for epoch in range(1, args.epochs + 1):
        model.train()
        ep_t = time.time()
        total_loss = 0.0
        n_batches  = 0

        for batch in train_dl:
            x_cont     = batch["x_cont"].to(device)
            x_cat      = {s: v.to(device) for s, v in batch["x_cat"].items()}
            minutes    = batch["minutes"].to(device)
            lengths    = batch["lengths"].to(device)
            labels     = batch["labels"].to(device)
            hist_seqs  = batch["hist_seqs"].to(device)
            hist_mins  = batch["hist_mins"].to(device)
            hist_glen  = batch["hist_glen"].to(device)
            hist_kmask = batch["hist_kmask"].to(device)

            B, T = labels.shape
            real_mask = torch.arange(T, device=device).unsqueeze(0) < lengths.unsqueeze(1)

            smooth = labels.clone()
            smooth[real_mask & (labels == 1)] = 1.0 - args.label_smooth
            smooth[real_mask & (labels == 0)] = args.label_smooth

            with torch.amp.autocast(device_type=device.type, enabled=use_amp, dtype=torch.bfloat16):
                probs = model(
                    x_cont, x_cat, minutes, lengths,
                    hist_seqs, hist_mins, hist_glen, hist_kmask,
                )
            probs = probs.float().nan_to_num(nan=0.5)
            loss = F.binary_cross_entropy(probs[real_mask].clamp(1e-6, 1 - 1e-6), smooth[real_mask].float())

            scaler_amp.scale(loss).backward()
            scaler_amp.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            scaler_amp.step(optimizer)
            scaler_amp.update()
            optimizer.zero_grad(set_to_none=True)

            total_loss += loss.item()
            n_batches  += 1

        scheduler.step()
        train_loss = total_loss / max(n_batches, 1)

        val_aucs   = eval_auc(model, val_dl,   device, use_amp)
        train_aucs = eval_auc(model, train_dl, device, use_amp)

        ep_s = time.time() - ep_t
        log.info(
            "Epoch %02d/%02d | loss=%.4f | "
            "AUC@5m=%.3f/%.3f  AUC@10m=%.3f/%.3f  AUC@end=%.3f/%.3f | %.1fs",
            epoch, args.epochs, train_loss,
            train_aucs["5m"], val_aucs["5m"],
            train_aucs["10m"], val_aucs["10m"],
            train_aucs["end"], val_aucs["end"],
            ep_s,
        )

        if val_aucs["end"] > best_val_auc:
            best_val_auc = val_aucs["end"]
            best_state   = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            patience_cnt = 0
        else:
            patience_cnt += 1
            if patience_cnt >= args.patience:
                log.info("Early stopping at epoch %d.", epoch)
                break

    log.info("Restoring best weights (val AUC@end=%.4f).", best_val_auc)
    if best_state is not None:
        model.load_state_dict(best_state)

    torch.save(model.state_dict(), MODEL_OUT)
    log.info("Saved model: %s", MODEL_OUT)

    with open(ARTIFACT_OUT, "wb") as f:
        pickle.dump({
            "cont_scaler": cont_scaler, "cat_vocab": cat_vocab,
            "cont_cols": cont_cols, "cat_groups": cat_groups,
            "K": args.k, "max_seq_len": args.max_seq_len,
            "best_val_auc": best_val_auc,
        }, f)
    log.info("Saved artifacts: %s", ARTIFACT_OUT)

    elapsed = time.time() - t0
    log.info("Done in %.1f s (%.1f min)", elapsed, elapsed / 60)
    print(f"\nBest val AUC@end: {best_val_auc:.4f}")


if __name__ == "__main__":
    main()
